meta_product_name: "Golfy Buddy"
meta_title: "Golfy Buddy - Play more golf, everywhere"
meta_description: "Golfing with buddies. Find upcoming games nearby with people who will enjoy to welcome you. Host a game: choose when, where and with whom. Find buddies that fits your personnality"
meta_image: "GolfyBuddyFB.png" # should exist in `app/assets/images/`
